[paths]
PRIV_KEY_PATH = tests/TEST-keys/TEST-private.key
PUB_KEY_PATH = tests/TEST-keys/TEST-public.key

[keys] 
SIZE = 2048
EXP = 65537

[misc]
PASS_HASH = b3b3ac6ead1c865a6056a78d93d1be8464e1461864561e26deb07cc394a87151