[paths]
priv_key_path = tests/TEST-keys/TEST-private.key
pub_key_path = tests/TEST-keys/TEST-public.key

[keys]
size = 2048
exp = 65537

[misc]
pass_hash = 33e0e5c29d37f692f7fc8082f4d4642458d414bafe1b7e36ef8e5ce918cecda7

