[paths]
priv_key_path = keys/private.key
pub_key_path = keys/public.key
symm_key_path = keys/symm.key

[keys]
size = 2048
exp = 65537

[misc]
pass_hash = e76e13a47a6ab9f42f96edc72ccc7417be2dd37a69ebc2a09c6944e6e5ead4ae

