[paths]
priv_key_path = keys/private.key
pub_key_path = keys/public.key
symm_key_path = keys/symm.key

[keys]
size = 2048
exp = 65537

[misc]
pass_hash = 0dadce16a6d1d9bd9aad50db21d3b7255c2fae3a8b6e2289ccf682299777b4d3

