[paths]
priv_key_path = tests/TEST-keys/TEST-private.key
pub_key_path = tests/TEST-keys/TEST-public.key

[keys]
size = 2048
exp = 65537

[misc]
pass_hash = 69f48c690edede2016e42a72691d543c6c140adc894af55ad25c08d84748cee5

