[IDENTITY]
common_name = 
mac = db:85:ed:17:e5:44
ip = 172.31.80.1

[SETTINGS]
allocated_storage = 20

[PATHS]
peer_storage_path = C:/Users/jjhea/OneDrive/WPI/PeerVault/master/backend/peer-storage/
tmp_storage_path = temp/

