[IDENTITY]
common_name = PickleLily
mac = f4:75:84:f6:0a:e0
ip = 169.254.97.173

[SETTINGS]
allocated_storage = 100.0

[PATHS]
peer_storage_path = C:/users/lilyb/Documents
tmp_storage_path = temp/

