[IDENTITY]
common_name = jjhealey_2
mac = cc:06:e5:6e:f9:d8
ip = 192.168.5.115

[SETTINGS]
allocated_storage = 50.0

[PATHS]
peer_storage_path = C:/Users/jjhea/peer-storage/
tmp_storage_path = temp/

